# Site settings
name: 계략
email: gyeryak77@gmail.com
author: GyeRyak
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/gyeryak/
baseurl: "/"
description: 잡다한 정보들
meta_description: 康志华;개인 블로그;배우고 생각하라;생각하고 배우지 않으면 아니 된다;삶은 그 이상이다;끊임없이 정진하라
motto: 모두에게 도움이 되도록
banner: 배우고 생각하지 않으면 아니 되고, 생각하지 않고 배우면 위험하다.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: gyeryak

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

